
# project_id should always be the first line
project_id = "zsczqlfwqegpfttwhdho"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true

[storage]
enabled = true

[[functions]]
name = "add-metrics"
path = "add-metrics"
verify_jwt = false

[[functions]]
name = "get-metrics"
path = "get-metrics"
verify_jwt = false

[[functions]]
name = "get-voiceflow-analytics"
path = "get-voiceflow-analytics"
verify_jwt = false
