// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsczqlfwqegpfttwhdho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzY3pxbGZ3cWVncGZ0dHdoZGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NDI0ODUsImV4cCI6MjA1NTExODQ4NX0.XYyO8166QE09csTDCcIkw-hwaMBJfr0D3L6ECCSIUMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);